### ISSUE TITLE
Turning on Class Health colors disables BuffHighlight

### ISSUE THREAD

**Issue by JeremyDwayne** [Vekkt/ElvUI_BuffHighlight#12]
Steps to reproduce:
1. Go into the ElvUI settings > UnitFrames > General > Colors, 
2. Enable Class Health instead of a custom health color
3. Reload

This disables the menu option for BuffHighlight, and existing highlights no longer show on unit frames. If you turn it off again and reload, BuffHighlight comes back in the menu and show on frames again.

If this is intentional, you may want to specify in your documentation that you cannot use class colors. I was extremely confused for a solid 2 weeks when my buff highlight just randomly stopped working. Figured this out last night that you can't use class colors on your unit frames' health.

**Comment by JeremyDwayne** [comment]
Looking through the code, this is intended. In that case, please make this warning visibile in the readme/description of the plugin. I have never seen a warning message saying to do this to reenable BuffHighlight. That may be a bug with your warning.

**Comment by Vekkt** [comment]
It is only written "recommanded" instead of "mandatory" in the readme, indeed.

Nonetheless the warning message should display at launch if you're using class colors, don't know why it doesnt for you.

I'm glad you could make it work tho.
