### ISSUE TITLE
doesn't appear to be working for me? 

### ISSUE THREAD

**Issue by allisonsteranko** [Vekkt/ElvUI_BuffHighlight#13]
Hi there. 

I'll be the first to say that I may not be using this correctly but as shown in the two screenshots - i've set colors for Atonement, and then when putting Atonement on my partymate i see no change? 

[Screenshots](https://imgur.com/a/wf2tG3X)

**Comment by Vekkt** [comment]
You are not using the correct spell id for atonement. The id of the buff is 194384.
