### ISSUE TITLE
BuffHighlight button not appearing on elvui menu

### ISSUE THREAD

**Issue by edumorais** [Vekkt/ElvUI_BuffHighlight#16]
Hiii!
I just downloaded the addon, but the button is not showing in the elvui menu
Ty for the help and nice work, keep it ip!

![ElvuiMenu](https://user-images.githubusercontent.com/19350127/96497853-a9632580-1221-11eb-9e79-aa2f725a41df.png)

**Comment by Ukkitop** [comment]
face same issue, could anyone tell me how to fix it?
