### ISSUE TITLE
Big performance hit

### ISSUE THREAD

**Issue by Nercus** [Vekkt/ElvUI_BuffHighlight#2]
I noticed an extreme performance hit due to the plugin. Addon CPU Usage shows it with a similar impact as Elvui itself.

 I tried it with ElvUI and ElvUI_BuffHighlight enabled. That led to the same result. In Nyalotha I noticed an immense fps difference (around 25 fps).

If you need more info just tell me!

**Comment by Vekkt** [comment]
thanks for the feedback. Is there a specific scenario in which the performance drop occurs ? Like a specific boss or zone ?

**Comment by Nercus** [comment]
In Nyalotha it was around 25 fps. In Group Content (Waycrest Manor) it was around 7-10 fps. 

I always tried to only use ElvUI and BuffHighlight and no other addon.

**Comment by Vekkt** [comment]
Could you share the result of the profiler after a raid or dungeon encounter ?

**Comment by Nercus** [comment]
I couldn't find the results from yesterday and tried it again today. It got a bit better (but smaller raid now) but still uses a lot of ressources (compared to i.e. Details)

![image](https://user-images.githubusercontent.com/48932939/83875639-c1854d00-a737-11ea-8e3c-c25a8032ba67.png)

**Comment by Nercus** [comment]
I got some more and important info for you. I'm lookin into this problem for several hours now and noticed something. The FPS Drop is not only caused by your plugin also ElvUI has a bigger impact if your plugin is enabled.

I used the [ElvUIDev](https://github.com/Resike/ElvUIDev) addon to check to updates of the modules of ElvUI and noticed something. The BackdropTexture of unitframes gets update way to often. Even out of fight. For more look into it here some pictures:

**Plugin Disabled (~1min;sitting in Garrison doing nothing;no group; started 30 secs after relog; no other addons enabled):**

_ElvUI Dev:_
![image](https://user-images.githubusercontent.com/48932939/83878135-f6939e80-a73b-11ea-8bf6-39c09a16f0ff.png)

_Addon CPU Usage:_

![image](https://user-images.githubusercontent.com/48932939/83878713-dadcc800-a73c-11ea-9b40-4953630ee02e.png)


**Plugin Enabled(~1min;sitting in Garrison doing nothing;no group; started 30 secs after relog; no other addons enabled):**

_ElvUI Dev:_
![image](https://user-images.githubusercontent.com/48932939/83878351-538f5480-a73c-11ea-9304-d9162dfb857b.png)

_Addon CPU Usage:_
![image](https://user-images.githubusercontent.com/48932939/83878527-93eed280-a73c-11ea-9648-4ed8556b85c7.png)

**Comment by Nercus** [comment]
Im not done with final testing, but i created a pull request. I changed it to update on COMBAT_LOG_EVENT_UNFILTERED. You can see the number how often each event fires in the pic below: 
![image](https://user-images.githubusercontent.com/48932939/83944322-fa3e2880-a802-11ea-9f8e-a5ba1ef9b031.png)

The fading options doesn't work anymore for now. I'll try to fix that. But the performance difference is huge.

**Comment by Nercus** [comment]
Ok I was a bit too quick with my pull request. Sorry for that.

There are several new problems with the change. But the cpu usage looks wonderful :D 

![image](https://user-images.githubusercontent.com/48932939/83944905-4a1eee80-a807-11ea-8261-8cc8dca1d77a.png)

**Comment by Vekkt** [comment]
I'm also working on a simple fix, which has no effect on the fading feature. Doing some benchmarks in raid rn

**Comment by Nercus** [comment]
Hey, I came up with a pretty efficient solution. Unfortunately the fading option doesnt work, because it would need a const update to check if aura duration is sub the threshold. I still have some testing to do, but it looks pretty promising (besides the fade option)

**Comment by Vekkt** [comment]
I found time to work a bit on the addon. It gave it a new look, as well as tackling this performance issue. 

Thats not perfect but I think there is a great improvement. And the fader still works
![BH_Profiling](https://user-images.githubusercontent.com/29548510/84570039-e0648e80-ad8a-11ea-8889-24093e07a88d.PNG)

**Comment by Nercus** [comment]
Im nearly done testing with my version which is even more efficient. I also found a solution to add the fade option as I looked into your new update. I hope i can make my pull request in the next days.

**Comment by Nercus** [comment]
Due to major issues with the way i updated the uf i stopped the development on my version. The performance gain compared to your current version would be marginal. 
If you want to update your Addon even further you can try to update on CLEU SPELL_AURA_APPLIED/REMOVED and hook to PostUpdateColor. So you only update single frames and not always all the frames.

Thanks for your good work.
