### ISSUE TITLE
Disabling class colors is actually required, not recommended

### ISSUE THREAD

**Issue by broizter** [Vekkt/ElvUI_BuffHighlight#20]
According to the readme here on GitHub "It is recommanded to play with uniform health colors (i.e. not class color health)". But when enabling this plugin you will get this message in game "ElvUI BuffHighlight: You are currently using class heath colors. Please disable this option in order to BuffHilight to work. (UnitFrames > General Options > Colors > Class Health" and the plugin will not load at all until you follow the instructions (does not even show up in the ElvUI settings). Maybe I'm missing something but there seems to be a conflict here.

**Comment by Vekkt** [comment]
Thanks for pointing that out. Changed to " _mandatory_ to play with uniform health colors"
