### ISSUE TITLE
Flickering ElvUI 12.43

### ISSUE THREAD

**Issue by lserman** [Vekkt/ElvUI_BuffHighlight#25]
When someone takes damage on ElvUI 12.43, the highlight color flickers the frame.

**Comment by blahblahrandomname** [comment]
The Buff Hightlight options also appear to be missing with the recent update to Elvui.  Experiencing the flickering bug as well.

**Comment by gotu0902** [comment]
Experiencing the same issues, trying a workaround by downgrading Elv to 12.41 and SLE to 4.27, seems to fix it, at least for the time being.
Missing the fixes for SLE's enhanced vehicle bar and some other things but hopefully it does the job until this awesome plugin is updated :)

**Comment by saki-rolling** [comment]
As on ElvUI 12.43 the unitframe headers are not available at the time that the plugin registers, so it's unable to hook onto the PostUpdateColor function.

The code needs to postpone BH:enablePlugin until a point of time where the unit frame headers are there.
