### ISSUE TITLE
Fade not working

### ISSUE THREAD

**Issue by Maynim** [Vekkt/ElvUI_BuffHighlight#27]
Hello, the "Fade" function does not work as it should, currently when the "Fading Threshold" is reached, the color of the frame is immediately tinted to the final color, ignoring the fade phase. "Refresh rate" does not affect this, as if it does not work at all.

**Comment by Vekkt** [comment]
The fade works as intended: while the remaining buff time is greater than the threshold, the frame is colored using the highlight color. When the remaining time is lower than the threshold, the frame color is set to the fade color. There is no "fade" phase (like some kind of gradient?).
