### ISSUE TITLE
Unitframe flicker when you take damage

### ISSUE THREAD

**Issue by WoWCraft** [Vekkt/ElvUI_BuffHighlight#4]
Since the 2.0 update, I experience issues that my unit frames flicker every time a player takes damage.

To replicate:

- Put the buff you highlight on yourself
- Take fall damage
- You will see the frame briefly flicker to it's non highlight color and then back to the highlight color.

I didn't have this issue pre 2.0

**Comment by Vekkt** [comment]
Wrong version was pushed for a couple of minutes after release... My bad. You're quick on updating!

**Comment by WoWCraft** [comment]
That's odd, Just used the new source from github updated my addon folder, same issue.

**Comment by WoWCraft** [comment]
Ok figured it out, your release is indeed not to blame. Well not directly at least.

It's the combination of this addon and using another addon:
https://www.tukui.org/addons.php?id=45

To reproduce just install your latest version and install the above UnitFramePlugin.

You will see a flicker every time a unit's health is updated.

Is this something that should be solved here or in the other addon?

Your previons (pre v2.X) version worked well together with the above addon.

**Comment by Vekkt** [comment]
you should always download the addon from tukui website: https://www.tukui.org/addons.php?id=148
Github is meant for developement, this is rarely a stable version.

Dont hesitate if you have further issues

**Comment by Vekkt** [comment]
Im gonna investigate yuor issue in the coming days, but you know, exam period...
