### ISSUE TITLE
Party target frames highlight

### ISSUE THREAD

**Issue by Vikthor77** [Vekkt/ElvUI_BuffHighlight#5]
Hello! I love this supplement, it makes healing very easy.
Couldn’t it be solved for Glimmer of Light to appear on the party target frame as a debuff?
Thanks,
Viktor

**Comment by Vekkt** [comment]
Hi, I'm glad you found my plug-in useful !

This plug-in is only about highlighting buffs, in the same way as the ElvUI's built-in debuff highlight feature does, so I have no plan to support debuff highlights, sorry.

I'm not sure to know what Party target frames are. It displays the current target for each party member near their frame ?
Maybe you can search a solution with the debuff highlight ?

**Comment by ckipps** [comment]
I love this idea.
I copied ElvUI_BuffHighlight (not master) in AddOns but the plugin doesnt show in the Elvui menu at the bottom left.
Any idea?
