### ISSUE TITLE
Awesome idea but doesn't show for me

### ISSUE THREAD

**Issue by ckipps** [Vekkt/ElvUI_BuffHighlight#6]
I love this idea.
I copied ElvUI_BuffHighlight (not master) in AddOns but the plugin doesnt show in the Elvui menu at the bottom left.
Any idea?

**Comment by ckipps** [comment]
![image](https://user-images.githubusercontent.com/48648335/86133959-055d3f00-bab7-11ea-9025-d592f79271a7.png)

As you can see it's installed but it's still not showing.

**Comment by Vekkt** [comment]
Weird. Works fine for me: 
![image](https://user-images.githubusercontent.com/29548510/86156487-5183a000-bb06-11ea-90c2-614864502d96.png)

Maybe a conflict with RedtuzkUI but I doubt it

**Comment by ckipps** [comment]
I'll reinstall Elvui etc and see if it works. Thanks for looking into it!

**Comment by Guille-Z** [comment]
I'm facing the same issue, strange enough an older version works, this commit made in january works for me. [here](https://github.com/Vekkt/ElvUI_BuffHighlight/tree/05bd35fdab808012e1f663d6f7635b05450495f9)

**Comment by ckipps** [comment]
> I'm facing the same issue, strange enough an older version works, this commit made in january works for me. [here](https://github.com/Vekkt/ElvUI_BuffHighlight/tree/05bd35fdab808012e1f663d6f7635b05450495f9)

Awesome, I'll give this a try!

 Thank you so much for the help

**Comment by Guille-Z** [comment]
Update: Latest ElvUI version seems to have fixed the issue, at least for me

**Comment by Marzipanbrot** [comment]
So I have an update on this... Just like the publisher of this issue the addon wont show in my elvUI. Now for some reason if I start ElvUI on a fresh Character it works fine. So I tried to log on my Main Character and try it with the install option from elvui and then it worked. So i tried to just copy my profile into the new one I just setup with the install option and it worked. But if I reload after doing that it is gone again. Hope that helps in fixing the issue.

**Comment by aliceop1** [comment]
Hello I have the same problem, the add-on installs but doesn't show for me in the EC panel.

I installed an old version and this does show, but doesn't work.
