### ISSUE TITLE
own buff

### ISSUE THREAD

**Issue by Vikthor77** [Vekkt/ElvUI_BuffHighlight#7]
is it possible for me to see only my own? because now the opponent’s glimmer also appears on my teammate as if it were my buff
sorry for my english
thanks

**Comment by Vekkt** [comment]
Hi,

Are you sure it is not the debuff highlight that does that ?

**Comment by Vikthor77** [comment]
hi,

for sure, because the debuff glimmer has the same color as the smooth one, while the magic debuff is blue by default

**Comment by Vekkt** [comment]
Could you provide me with this information please:

In which context does this happen: world PvP, arena, battlegrounds... ?
On which unit frames: Target frame, party frames... ? 

thank you

**Comment by Vikthor77** [comment]
WPvP and party frames.
but with the current elvui update, highlight works without the addon
interesting

**Comment by Vikthor77** [comment]
nothing, yet it was a debuff highlight, sorry I robbed you of your time
thanks for the great addon
