### ISSUE TITLE
Broken with latest ElvUI update

### ISSUE THREAD

**Issue by Malenkie** [Vekkt/ElvUI_BuffHighlight#8]
Hey I really love this addon, unfortunately it stopped working with the latest ElvUI update (Version 11.43 [ July 9th 2020 ]). Are you still maintaining this? I tried asking for help in the ElvUI discord but was told it would never be in base ElvUI because it would clash with debuff highlight.

**Comment by Vekkt** [comment]
I have not found time to test the new release, nor to keep the plugin update. I'll try to do it in the next couple of days.

**Comment by Malenkie** [comment]
Thanks so much. It just randomly started working again now, so I don't know what the issue is, and don't have the knowledge or skill to find out, but I appreciate your time working on it.

**Comment by Vekkt** [comment]
If you have any information that could be relevant, like a specific set up in which the bugs happens, please let me know !
