### ISSUE TITLE
Debuff Color Override

### ISSUE THREAD

**Issue by Nercus** [Vekkt/ElvUI_BuffHighlight#9]
With the latest update the debuff color mixes with the buff highlight color. Neither debuffs overriding buff highlight nor vise-versa. It actually mixes the colors like seen in the picture below
![Unbenannt](https://user-images.githubusercontent.com/48932939/87341014-2f980d80-c549-11ea-8880-cdf971a4a4d6.png)
Left to right: Debuff + Buff Highlight/ Debuff only/ Buff highlight only

**Comment by Vekkt** [comment]
Thanks for noticing. Should be fixed. 

I'll upload the new version on tukui's website once I'm sure it is fixed

**Comment by Nercus** [comment]
Thanks works good now. I just tested some options around though. There is still some wierd glitching (flashing of the frames) with the option `Overwrite Debuff`. Just wanted to report that aswell before closing the issue, even without using that option myself.
